//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amadeus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amadeus.Resources.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} eliminuje **{1}**!.
        /// </summary>
        internal static string BattleRoyale_Eliminates {
            get {
                return ResourceManager.GetString("BattleRoyale.Eliminates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komenda musi być użyta na kanale tekstowym!.
        /// </summary>
        internal static string BattleRoyale_MustBeUsedInTextChannel {
            get {
                return ResourceManager.GetString("BattleRoyale.MustBeUsedInTextChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za mało uczestników!.
        /// </summary>
        internal static string BattleRoyale_NotEnoughPlayers {
            get {
                return ResourceManager.GetString("BattleRoyale.NotEnoughPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nic się nie dzieje....
        /// </summary>
        internal static string BattleRoyale_NothingHappens {
            get {
                return ResourceManager.GetString("BattleRoyale.NothingHappens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string BattleRoyale_PlayerListConnector {
            get {
                return ResourceManager.GetString("BattleRoyale.PlayerListConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  i .
        /// </summary>
        internal static string BattleRoyale_PlayerListLastConnector {
            get {
                return ResourceManager.GetString("BattleRoyale.PlayerListLastConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uczestnicy.
        /// </summary>
        internal static string BattleRoyale_Players {
            get {
                return ResourceManager.GetString("BattleRoyale.Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczynanie gry!.
        /// </summary>
        internal static string BattleRoyale_StartingGame {
            get {
                return ResourceManager.GetString("BattleRoyale.StartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Royale.
        /// </summary>
        internal static string BattleRoyale_Title {
            get {
                return ResourceManager.GetString("BattleRoyale.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0} wygrywa grę! 🎉**.
        /// </summary>
        internal static string BattleRoyale_Wins {
            get {
                return ResourceManager.GetString("BattleRoyale.Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeprowadź rozgrywkę Battle Royale..
        /// </summary>
        internal static string br_description {
            get {
                return ResourceManager.GetString("br.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to br.
        /// </summary>
        internal static string br_name {
            get {
                return ResourceManager.GetString("br.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uczestnicy walki oddzieleni spacją.
        /// </summary>
        internal static string br_players_description {
            get {
                return ResourceManager.GetString("br.players.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uczestnicy.
        /// </summary>
        internal static string br_players_name {
            get {
                return ResourceManager.GetString("br.players.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość wiadomości do usunięcia.
        /// </summary>
        internal static string purge_count_description {
            get {
                return ResourceManager.GetString("purge.count.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilość.
        /// </summary>
        internal static string purge_count_name {
            get {
                return ResourceManager.GetString("purge.count.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto {0} wiadomości!.
        /// </summary>
        internal static string Purge_DeletedCount {
            get {
                return ResourceManager.GetString("Purge.DeletedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń kilka poprzednich wiadomości..
        /// </summary>
        internal static string purge_description {
            get {
                return ResourceManager.GetString("purge.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieodpowiednia ilość wiadomości!
        ///Podaj liczbę z zakresu 1 do {0}..
        /// </summary>
        internal static string Purge_IncorrectMessageCount {
            get {
                return ResourceManager.GetString("Purge.IncorrectMessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można tego użyć na tym kanale!.
        /// </summary>
        internal static string Purge_InvalidChannelType {
            get {
                return ResourceManager.GetString("Purge.InvalidChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to czyść.
        /// </summary>
        internal static string purge_name {
            get {
                return ResourceManager.GetString("purge.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź statystyki bota..
        /// </summary>
        internal static string statistics_description {
            get {
                return ResourceManager.GetString("statistics.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyznany XP ⚔️.
        /// </summary>
        internal static string Statistics_GrantedExpLabel {
            get {
                return ResourceManager.GetString("Statistics.GrantedExpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statystyki.
        /// </summary>
        internal static string statistics_name {
            get {
                return ResourceManager.GetString("statistics.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping ⌛.
        /// </summary>
        internal static string Statistics_PingLabel {
            get {
                return ResourceManager.GetString("Statistics.PingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytaty 📜.
        /// </summary>
        internal static string Statistics_QuoteLabel {
            get {
                return ResourceManager.GetString("Statistics.QuoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki 📊.
        /// </summary>
        internal static string Statistics_StatsHeader {
            get {
                return ResourceManager.GetString("Statistics.StatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmy 🎥.
        /// </summary>
        internal static string Statistics_VideoLabel {
            get {
                return ResourceManager.GetString("Statistics.VideoLabel", resourceCulture);
            }
        }
    }
}
